# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

services:
  urlshortener-api:
    image: ${DOCKER_REGISTRY-}urlshortenerapi
    container_name: UrlShortener.Api
    platform: linux/amd64
    build:
      context: .
      dockerfile: src/url-shortener-api/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

  urlshortener-db:
    image: ${DOCKER_REGISTRY-}mcr.microsoft.com/mssql/server:2022-latest
    container_name: UrlShortener.Db
    platform: linux/amd64
    volumes:
      - ./.containers/database:/var/opt/mssql/data
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Strong_Password1234!"

  urlshortener-cache:
    image: ${DOCKER_REGISTRY-}redis:latest
    container_name: UrlShortener.Cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  urlshortener-db-data:

networks:
  default:
    name: urlshortener-network
